'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' (Partial) class diagram for EMFViews.core

@startuml

/' Theming '/

title emfviews.core

set namespaceseparator none
skinparam shadowing false
skinparam classAttributeIconSize 0

skinparam class {
  BackgroundColor<<EMF>> #f0f0f0
  BorderColor<<EMF>> #cdcdcd
  BackgroundColor #fff
  BorderColor #aaa
}

skinparam packageBorderColor #888

skinparam stereotype {
  CBackgroundColor #fff
  ABackgroundColor #fff
  IBackgroundColor #fff
}

skinparam arrow {
  Color #333
  FontColor #aaa
}

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' EMF Package

' not actually inside a package{} block because it over-constrains the
' contained classes

interface Resource <<EMF>> {
  +load()
  +save()
  +getContents()
  +getResourceSet()
}

class ResourceImpl <<EMF>> {
  #doLoad()
  #doSave()
  +getContents()
  +getResourceSet()
}

class EStoreEObjectImpl <<EMF>> {
}

interface EStore <<EMF>> {
  +get(EObject, EStructuralFeature, int): Object
  +set(EObject, EStructuralFeature, int, Object): Object
}

interface EObject <<EMF>> {
}

interface EStructuralFeature <<EMF>> {
}

interface ResourceSet <<EMF>> {
}

hide EObject members
hide EStructuralFeature members
hide EStoreEObjectImpl members
hide ResourceSet members

Resource <|.. ResourceImpl
EStoreEObjectImpl .left> EStore

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' VirtualLinks package

package emfviews.virtuallinks {

  interface VirtualLinks {
  }

  interface VirtualLink {
    +getName(): String
  }

  interface Filter {
  }

  interface Association {
  }

  interface LinkedElement {
    +getElementRef(): String
    +getModelRef(): String
  }

}

hide VirtualLinks members
hide Filter members
hide Association members

VirtualLinks "1" *-- "0..*" VirtualLink   /': virtualLinks '/
VirtualLinks "1" *-- "0..*" LinkedElement /': linkedElements '/

VirtualLink <|.. Association
VirtualLink <|.. Filter

Association --> "1" LinkedElement    /' : sourceElement '/
Association --> "0..*" LinkedElement /' : targetElements '/

Filter --> "1" LinkedElement    /' : filteredElement '/

/' hide VirtualLinks   '/

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' EMFViews.elements/rules

abstract class VirtualElement {
}

class ReproduceElementImpl {
}

class VirtualAssociation {
  +get(int): Object
  +set(EObject, int): Object
}

abstract class TranslationRule {
}

class ReproduceRule <<Singleton>> {
  +get(EObject, ...)
  +set(EObject, ...)
}

class VirtualModelList<E> {
  +get(int): E
  +size(): int
}


hide VirtualElement members
hide ReproduceElementImpl members
hide TranslationRule members

EStoreEObjectImpl <|-- VirtualElement
VirtualElement <|-- ReproduceElementImpl
VirtualElement "1" o-left "1" TranslationRule /' : translationRule '/

ReproduceElementImpl o-- "1" EObject               /' : concreteElement '/
ReproduceElementImpl o-- "0..*" VirtualAssociation /' : virtualAssociations '/
ReproduceElementImpl o-- "1" ReproduceRule         /' : translationRule '/
ReproduceElementImpl .[norank,#ccc].> View
ReproduceElementImpl .[norank,#ccc].> MetamodelManager
/' ReproduceElementImpl .[norank,#ccc].> EStructuralFeature '/

VirtualAssociation --> "1" EObject            /' : container '/
VirtualAssociation --> "0..*" EObject         /' : referencedElements '/
VirtualAssociation --> "1" EStructuralFeature /' : virtualFeature '/
VirtualAssociation .[norank,#ccc].> View

EStore <|.. TranslationRule
TranslationRule <|-- ReproduceRule

ReproduceRule .[norank,#ccc].> View
ReproduceRule .[norank,#ccc].> MetamodelManager
ReproduceRule .[norank,#ccc].> VirtualModelList
ReproduceRule .[norank,#ccc].> VirtualAssociation

VirtualModelList --> "1" View   /' : virtualModel '/
VirtualModelList .[norank,#ccc].> VirtualLinkManager

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' EMFViews.core

abstract class View {
  #contributingModelsURIs: String
  #contributingMetamodelsURIs: String
  #doSave()
  +getContents()
  #setVirtualContents()
  +translateToVirtualElement(EObject): EObject
}

class Viewpoint {
  -contributingEPackages: List<EPackage>
  #doLoad()
  #doSave()
  +getContents()
  +getResourceSet()
}

class EView {
  #doLoad()
}

class VirtualLinkManager {
  +initialize()
  +getVirtualElement(EObject): EObject
}

class MetamodelManager {
  -contributingMetamodels: List<EPackage>
  -buildMaps()
  +getVirtualAssociation(EObject, String name): EStructuralFeature
  +translateToVirtualFeature(EObject, EStructuralFeature): EStructuralFeature
  +translateFromVirtualFeature(EObject, EStructuralFeature): EStructuralFeature
}

class LinksProjector {
  +load(VirtualLinks)
}

class VirtualLinksDelegator {
  +createVirtualModelLinks(URI, List<Resource>)
}

interface IVirtualLinksDelegate {
  +createVirtualModelLinks(String, URI, List<Resource>)
}

class EclDelegate {
  +createVirtualModelLinks(String, URI, List<Resource>)
}

/'
 ' note left
 '   Created by VirtualLinkManager and
 '   discarded after it has created
 '   ReproduceElement for each Association
 ' end note
 '/

class VirtualContents<E> {
  +get(int): E
  +set(int, E)
  +size(): int
}

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Relationships

ResourceImpl <|-- View
View "1" -left "1" VirtualLinkManager
View "1" -right "1" MetamodelManager
View "1" -- "1" VirtualContents
View o-- "1" ResourceSet

View <|-- EView
EView --> "1" Viewpoint              /' : viewpoint '/
EView .[norank,#ccc].> VirtualLinkManager
EView .[norank,#ccc].> MetamodelManager
EView ..> VirtualLinksDelegator

VirtualLinksDelegator o-- "1" IVirtualLinksDelegate

IVirtualLinksDelegate <|.. EclDelegate

EclDelegate .[norank,#ccc].> VirtualLinks
EclDelegate .[norank,#ccc].> Association
EclDelegate .[norank,#ccc].> LinkedElement

ResourceImpl <|-- Viewpoint
Viewpoint o-[norank]- "1" ResourceSet   /' : virtualResourceSet '/
Viewpoint "1" -[norank]- "1" VirtualContents
Viewpoint .[norank,#ccc].> VirtualLinks
Viewpoint .[norank,#ccc].> Association
Viewpoint .[norank,#ccc].> LinkedElement
Viewpoint .[norank,#ccc].> Filter

MetamodelManager --> "1" Viewpoint /' viewpoint '/
MetamodelManager --> "1" View /' virtualModel '/
MetamodelManager .[norank,#ccc].> ReproduceElementImpl

VirtualLinkManager --> "1" VirtualLinks /' weavingModel '/
VirtualLinkManager .[norank,#ccc].> ReproduceElementImpl
VirtualLinkManager .[norank,#ccc]. LinksProjector

LinksProjector --> "1" View     /'virtualModel '/
LinksProjector .[norank,#ccc].> MetamodelManager
LinksProjector .[norank,#ccc].> VirtualLinks
LinksProjector .[norank,#ccc].> Association
LinksProjector .[norank,#ccc].> LinkedElement
LinksProjector .[norank,#ccc].> ReproduceElementImpl

EView -[hidden]> VirtualContents
VirtualContents -[hidden]> ResourceSet

@enduml
