'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Object diagram for EMFViews.core
'
' These are all the relevant objects in the heap created by EMFViews after
' EView.load().
'
' Arrow semantics:
' A o--  B := A has B as attribute
' A o--o B := A has B as attribute, and B has A as attribute
' A -->  B := A creates B (but does not hold B as attribute)
' A ..>  B := A holds a weak reference to B (HashMap nodes)

@startuml

/' Theming '/

title Object diagram for EView.load()

set namespaceseparator none
skinparam shadowing false
skinparam classAttributeIconSize 0

skinparam class {
  BackgroundColor<<EMF>> #f0f0f0
  BorderColor<<EMF>> #cdcdcd
  BackgroundColor<<Java>> #f0f0f0
  BorderColor<<Java>> #cdcdcd
  BackgroundColor #fff
  BorderColor #aaa
}

skinparam packageBorderColor #888

skinparam stereotype {
  CBackgroundColor #fff
  ABackgroundColor #fff
  IBackgroundColor #fff
}

skinparam arrow {
  Color #333
  FontColor #333
  FontSize 11
}

skinparam note {
  BackgroundColor #fff
  BorderColor #aaa
}

hide class circle
hide class methods

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' EView objects

class EView {
  uri: resources/views/minimal/view.eview
}

class Properties <<Java>> {
  weavingModel: "resources/views/minimal/weaving.xmi"
  contributingModels: "resources/models/minimal.xmi"
  viewpoint: "resources/viewpoints/minimal/viewpoint.eviewpoint"
}

class ResourceSetImpl <<EMF>> {
  resources: []
}

class Viewpoint {
  uri: resources/viewpoints/minimal/viewpoint.eviewpoint
  matchingModel: ""
  contributingMetamodels: "resources/metamodels/minimalref.ecore"
}

class Properties/2 <<Java>> {
  matchingModel: ""
  weavingModel: "resources/viewpoints/minimal/weaving.xmi"
  contributingMetamodels: "resources/metamodels/minimalref.ecore"
}

class ResourceSetImpl/2 <<EMF>> {
}

class EPackageRegistryImpl <<EMF>> {
  delegateRegistry: EPackage.Registry.INSTANCE
}

class EPackageImpl <<EMF>> {
  name: "minimalref"
  nsURI: http://inria.fr/atlanmod/emfviews/tests/minimalref
}

class EClassImpl <<EMF>> {
  name: "A"
}

class EReferenceImpl <<EMF>> {
  name: "manyB"
  lowerBound: 0
  upperBound: -1
}

class EClassImpl/2 <<EMF>> {
  name: "B"
}

class EReferenceImpl/2 <<EMF>> {
  name: "parentA"
  lowerBound: 0
  upperBound: 1
}

class EPackageImpl/2 <<EMF>> {
  name: "minimalref"
  nsURI: http://inria.fr/atlanmod/emfviews/tests/minimalref
}

class EClassImpl/3 <<EMF>> {
  name: "A"
}

class EReferenceImpl/3 <<EMF>> {
  name: "manyB"
  lowerBound: 0
  upperBound: -1
}

class EClassImpl/4 <<EMF>> {
  name: "B"
}

class EReferenceImpl/4 <<EMF>> {
  name: "parentA"
  lowerBound: 0
  upperBound: 1
}

class ResourceSetImpl/3 <<EMF>> {
}

class XMIResourceImpl <<EMF>> {
  uri: resources/viewpoints/minimal/weaving.xmi
}

class VirtualLinksImpl {
}

class LinkedElement {
  name: "manyB"
  elementRef: "minimalref.A.manyB"
  modelRef: "http://inria.fr/atlanmod/emfviews/tests/minimalref"
}

class FilterImpl {
  name: "manyB"
}

class EPackageRegistryImpl/2 <<EMF>> {
}

class EPackageImpl/3 <<EMF>> {
  name: "minimalref"
  nsURI: http://inria.fr/atlanmod/emfviews/tests/minimalref
}

class EClassImpl/5 <<EMF>> {
  name: "A"
}

class EReferenceImpl/5 <<EMF>> {
  name: "manyB"
  lowerBound: 0
  upperBound: -1
}

class EClassImpl/6 <<EMF>> {
  name: "B"
}

class EReferenceImpl/6 <<EMF>> {
  name: "parentA"
  lowerBound: 0
  upperBound: 1
}

class HashMap <<Java>> {
}

class HashMap$Node0 <<Java>> {
}

class HashMap$Node1 <<Java>> {
}

class HashMap/2 <<Java>> {
}

class HashMap/2$Node0 <<Java>> {
}

class XMIResourceImpl/2 <<EMF>> {
  uri: resources/models/minimal.xmi
}

class DynamicEObjectImpl <<EMF>> {
}

class DynamicEObjectImpl/2 <<EMF>> {
}

class DynamicEObjectImpl/3 <<EMF>> {
}

class ResourceSetImpl/4 <<EMF>> {
}

class XMIResourceImpl/3 <<EMF>> {
}

class VirtualLinksImpl/2 {
  linkedElements: null
  virtualLinks: null
}

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' EView relationships

EView o-- Properties : properties
EView o-- ResourceSetImpl : virtualResourceSet
EView o-- Viewpoint

Viewpoint o-- "Properties/2" : properties
Viewpoint o-- "ResourceSetImpl/2" : virtualResourceSet
Viewpoint o-- EPackageImpl : contributingEPackages

EPackageImpl o-- EClassImpl : eClassifiers[0]
EPackageImpl o-- "EClassImpl/2" : eClassifiers[1]

EClassImpl o-- EReferenceImpl : eStructuralFeatures[0]
"EClassImpl/2" o-- "EReferenceImpl/2" : eStructuralFeatures[0]

EReferenceImpl o-o "EReferenceImpl/2" : eOpposite

"ResourceSetImpl/2" o-- EPackageRegistryImpl : packageRegistry

EPackageRegistryImpl o-- "EPackageImpl/2" : "http://inria.fr/emfviews/tests/minimalref"

"EPackageImpl/2" o-- "EClassImpl/3" : eClassifiers[0]
"EPackageImpl/2" o-- "EClassImpl/4" : eClassifiers[1]

/' "EClassImpl/3" o-- "EReferenceImpl/3" : eStructuralFeatures[0] '/
"EClassImpl/4" o-- "EReferenceImpl/4" : eStructuralFeatures[0]

/' "EReferenceImpl/3" o-o "EReferenceImpl/4" : eOpposite '/

Viewpoint --> "ResourceSetImpl/3" : loadWeavingModel()
"ResourceSetImpl/3" o-- XMIResourceImpl : resources[0]
Viewpoint o-- XMIResourceImpl : weavingModelResource
XMIResourceImpl o-- VirtualLinksImpl : contents[0]

VirtualLinksImpl o-- LinkedElement : linkedElements[0]
VirtualLinksImpl o-- FilterImpl : virtualLinks[0]
FilterImpl o- LinkedElement : filteredElement

Viewpoint o-- "EReferenceImpl/3" : hiddenAttributes[0]
Viewpoint o-- VirtualContents : virtualContents

VirtualContents o-- "EPackageImpl/2" : subLists[0][0]

ResourceSetImpl o-- "EPackageRegistryImpl/2" : packageRegistry
"EPackageRegistryImpl/2" o-- "EPackageImpl/3" : "http://inria.fr/emfviews/tests/minimalref"

"EPackageImpl/3" o-- "EClassImpl/5" : eClassifiers[0]
"EPackageImpl/3" o-- "EClassImpl/6" : eClassifiers[1]

"EClassImpl/5" o-- "EReferenceImpl/5" : eStructuralFeatures[0]
"EClassImpl/6" o-- "EReferenceImpl/6" : eStructuralFeatures[0]

"EReferenceImpl/5" o-o "EReferenceImpl/6" : eOpposite

EView "metamodelManager" o--o "virtualModel" MetamodelManager
MetamodelManager o-- Viewpoint : viewpoint
MetamodelManager o-- "EPackageImpl/3" : contributingMetamodels[0]

MetamodelManager o-- HashMap : concreteToVirtualClass
HashMap o-- HashMap$Node0
HashMap o-- HashMap$Node1

HashMap$Node0 ..> "EClassImpl/5" : key
HashMap$Node0 ..> "EClassImpl/3" : value

HashMap$Node1 ..> "EClassImpl/6" : key
HashMap$Node1 ..> "EClassImpl/4" : value

MetamodelManager o-- "HashMap/2" : concreteToVirtualFeature
/' MetamodelManager o-- HashMap : virtualToConcreteFeature '/

"HashMap/2" o-- "HashMap/2$Node0"
"HashMap/2$Node0" o-- "EReferenceImpl/6" : key
"HashMap/2$Node0" o-- "EReferenceImpl/4" : value

ResourceSetImpl o-- "XMIResourceImpl/2" : resources[0]

"XMIResourceImpl/2" o-- DynamicEObjectImpl : contents[0]
"XMIResourceImpl/2" o-- "DynamicEObjectImpl/2" : contents[0]
"XMIResourceImpl/2" o-- "DynamicEObjectImpl/3" : contents[0]

DynamicEObjectImpl o-- "EClassImpl/5" : eClass
"DynamicEObjectImpl/2" o-- "EClassImpl/6" : eClass
"DynamicEObjectImpl/3" o-- "EClassImpl/6" : eClass

EView "vLinkManager" o--o "virtualModel" VirtualLinkManager

VirtualLinkManager --> "ResourceSetImpl/4"
"ResourceSetImpl/4" o-- "XMIResourceImpl/3" : resources[0]
"XMIResourceImpl/3" o-- "VirtualLinksImpl/2" : contents[0]

VirtualLinkManager o-- "VirtualLinksImpl/2" : weavingModel

VirtualLinkManager --> LinksProjector
LinksProjector o-- EView

VirtualLinkManager o-- "HashMap/3" : virtualLinks
"HashMap/3" o-- "HashMap/3$Node0"
"HashMap/3$Node0" ..> DynamicEObjectImpl : key
"HashMap/3$Node0" ..> ReproduceElementImpl : value

ReproduceElementImpl o-- DynamicEObjectImpl : concreteElement
ReproduceElementImpl o-- EStoreEPropertiesHolderImpl : eProperties
EStoreEPropertiesHolderImpl o-- "EClassImpl/3" : eClass
EStoreEPropertiesHolderImpl o-- EView : eResource
ReproduceElementImpl o-- ReproduceRule : translationRule
ReproduceElementImpl o-- ReproduceRule : eStore

"HashMap/3" o-- "HashMap/3$Node1"
"HashMap/3$Node1" ..> "DynamicEObjectImpl/2" : key
"HashMap/3$Node1" ..> "ReproduceElementImpl/2" : value

"ReproduceElementImpl/2" o-- "DynamicEObjectImpl/2" : concreteElement
"ReproduceElementImpl/2" o-- "EStoreEPropertiesHolderImpl/2" : eProperties
"EStoreEPropertiesHolderImpl/2" o-- "EClassImpl/4" : eClass
"EStoreEPropertiesHolderImpl/2" o-- EView : eResource
"ReproduceElementImpl/2" o-- ReproduceRule : translationRule
"ReproduceElementImpl/2" o-- ReproduceRule : eStore

"HashMap/3" o-- "HashMap/3$Node2"
"HashMap/3$Node2" ..> "DynamicEObjectImpl/3" : key
"HashMap/3$Node2" ..> "ReproduceElementImpl/3" : value

"ReproduceElementImpl/3" o-- "DynamicEObjectImpl/3" : concreteElement
"ReproduceElementImpl/3" o-- "EStoreEPropertiesHolderImpl/3" : eProperties
"EStoreEPropertiesHolderImpl/3" o-- "EClassImpl/4" : eClass
"EStoreEPropertiesHolderImpl/3" o-- EView : eResource
"ReproduceElementImpl/3" o-- ReproduceRule : translationRule
"ReproduceElementImpl/3" o-- ReproduceRule : eStore

EView o-- "VirtualContents/2" : virtualContents
"VirtualContents/2" o-- ReproduceElementImpl : sublists[0][0]
"VirtualContents/2" o-- "ReproduceElementImpl/2" : sublists[0][1]
"VirtualContents/2" o-- "ReproduceElementImpl/3" : sublists[0][2]

@enduml
