'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' Object diagram for EMFViews.core
'
' These are all the relevant objects in the heap created by EMFViews after
' EView.load().  (Made on commit 076c71909692d4f984f7e86fd30363076bd7dfe3)
'
' Arrow semantics:
' A o--  B := A has B as attribute
' A o--o B := A has B as attribute, and B has A as attribute
' A -->  B := A creates B (but does not hold B as attribute)
' A ..>  B := A holds a weak reference to B (HashMap nodes)

@startuml

/' Theming '/

title Object diagram for EView.load()

set namespaceseparator none
skinparam shadowing false
skinparam classAttributeIconSize 0

skinparam class {
  BackgroundColor<<EMF>> #f0f0f0
  BorderColor<<EMF>> #cdcdcd
  BackgroundColor<<Java>> #f0f0f0
  BorderColor<<Java>> #cdcdcd
  BackgroundColor #fff
  BorderColor #aaa
}

skinparam packageBorderColor #888

skinparam stereotype {
  CBackgroundColor #fff
  ABackgroundColor #fff
  IBackgroundColor #fff
}

skinparam arrow {
  Color #333
  FontColor #333
  FontSize 11
}

skinparam note {
  BackgroundColor #fff
  BorderColor #aaa
}

hide class circle
hide class methods

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' EView objects
'
' Numbers after the class name refer to the object ID reported by the Eclipse
' debugger for a single run.  These numbers tend to change every run, but they
' were useful in establishing the relationships.

class EView/83 {
  uri: resources/views/minimal/view.eview
}

class Properties/104 <<Java>> {
  weavingModel: "resources/views/minimal/weaving.xmi"
  contributingModels: "resources/models/minimal.xmi"
  viewpoint: "resources/viewpoints/minimal/viewpoint.eviewpoint"
}

class ResourceSetImpl/122 <<EMF>> {
  resources: []
}

class Viewpoint/113 {
  uri: resources/viewpoints/minimal/viewpoint.eviewpoint
  matchingModel: ""
  contributingMetamodels: "resources/metamodels/minimalref.ecore"
}

class Properties/381 <<Java>> {
  matchingModel: ""
  weavingModel: "resources/viewpoints/minimal/weaving.xmi"
  contributingMetamodels: "resources/metamodels/minimalref.ecore"
}

class ResourceSetImpl/448 <<EMF>> {
}

class EPackageRegistryImpl/471 <<EMF>> {
  delegateRegistry: EPackage.Registry.INSTANCE
}

class EPackageImpl/384 <<EMF>> {
  name: "minimalref"
  nsURI: http://inria.fr/atlanmod/emfviews/tests/minimalref
}

class EClassImpl/396 <<EMF>> {
  name: "A"
}

class EReferenceImpl/414 <<EMF>> {
  name: "manyB"
  lowerBound: 0
  upperBound: -1
}

class EClassImpl/397 <<EMF>> {
  name: "B"
}

class EReferenceImpl/417 <<EMF>> {
  name: "parentA"
  lowerBound: 0
  upperBound: 1
}

class EPackageImpl/505 <<EMF>> {
  name: "minimalref"
  nsURI: http://inria.fr/atlanmod/emfviews/tests/minimalref
}

class EClassImpl/173 <<EMF>> {
  name: "A"
}

class EReferenceImpl/453 <<EMF>> {
  name: "manyB"
  lowerBound: 0
  upperBound: -1
}

class EClassImpl/189 <<EMF>> {
  name: "B"
}

class EReferenceImpl/259 <<EMF>> {
  name: "parentA"
  lowerBound: 0
  upperBound: 1
}

class ResourceSetImpl/519 <<EMF>> {
}

class XMIResourceImpl/449 <<EMF>> {
  uri: resources/viewpoints/minimal/weaving.xmi
}

class VirtualLinksImpl/527 {
}

class LinkedElementImpl/540 {
  name: "manyB"
  elementRef: "minimalref.A.manyB"
  modelRef: "http://inria.fr/atlanmod/emfviews/tests/minimalref"
}

class FilterImpl/548 {
  name: "manyB"
}

class EPackageRegistryImpl/672 <<EMF>> {
}

class EPackageImpl/212 <<EMF>> {
  name: "minimalref"
  nsURI: http://inria.fr/atlanmod/emfviews/tests/minimalref
}

class EClassImpl/167 <<EMF>> {
  name: "A"
}

class EReferenceImpl/345 <<EMF>> {
  name: "manyB"
  lowerBound: 0
  upperBound: -1
}

class EClassImpl/188 <<EMF>> {
  name: "B"
}

class EReferenceImpl/256 <<EMF>> {
  name: "parentA"
  lowerBound: 0
  upperBound: 1
}

class HashMap/150 <<Java>> {
}

class HashMap$Node/163 <<Java>> {
}

class HashMap$Node/165 <<Java>> {
}

class HashMap/151 <<Java>> {
}

class HashMap$Node/254 <<Java>> {
}

class XMIResourceImpl/678 <<EMF>> {
  uri: resources/models/minimal.xmi
}

class DynamicEObjectImpl/586 <<EMF>> {
}

class DynamicEObjectImpl/604 <<EMF>> {
}

class DynamicEObjectImpl/609 <<EMF>> {
}

class ResourceSetImpl/663 <<EMF>> {
}

class XMIResourceImpl/656 <<EMF>> {
  uri: resources/models/weaving.xmi
}

class VirtualLinksImpl/578 {
  linkedElements: null
  virtualLinks: null
}

class EStoreEPropertiesHolderImpl/621 <<EMF>> {
}

class EStoreEPropertiesHolderImpl/651 <<EMF>> {
}

class EStoreEPropertiesHolderImpl/641 <<EMF>> {
}

class HashMap/577 <<Java>> {
}

class HashMap$Node/582 <<Java>> {
}

class HashMap$Node/583 <<Java>> {
}

class HashMap$Node/584 <<Java>> {
}

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
' EView relationships

"EView/83" o-- "Properties/104" : properties
"EView/83" o-- "ResourceSetImpl/122" : virtualResourceSet
"EView/83" o-- "Viewpoint/113"

"Viewpoint/113" o-- "Properties/381" : properties
"Viewpoint/113" o-- "ResourceSetImpl/448" : virtualResourceSet
"Viewpoint/113" o-- "EPackageImpl/384" : contributingEPackages

"EPackageImpl/384" o-- "EClassImpl/396" : eClassifiers[0]
"EPackageImpl/384" o-- "EClassImpl/397" : eClassifiers[1]

"EClassImpl/396" o-- "EReferenceImpl/414" : eStructuralFeatures[0]
"EClassImpl/397" o-- "EReferenceImpl/417" : eStructuralFeatures[0]

"EReferenceImpl/414" o-o "EReferenceImpl/417" : eOpposite

"ResourceSetImpl/448" o-- "EPackageRegistryImpl/471" : packageRegistry

"EPackageRegistryImpl/471" o-- "EPackageImpl/505" : "http://inria.fr/emfviews/tests/minimalref"

"EPackageImpl/505" o-- "EClassImpl/173" : eClassifiers[0]
"EPackageImpl/505" o-- "EClassImpl/189" : eClassifiers[1]

/' "EClassImpl/173" o-- "EReferenceImpl/453" : eStructuralFeatures[0] '/
"EClassImpl/189" o-- "EReferenceImpl/259" : eStructuralFeatures[0]

/' "EReferenceImpl/453" o-o "EReferenceImpl/259" : eOpposite '/

"Viewpoint/113" --> "ResourceSetImpl/519" : loadWeavingModel()
"ResourceSetImpl/519" o-- "XMIResourceImpl/449" : resources[0]
"Viewpoint/113" o-- "XMIResourceImpl/449" : weavingModelResource
"XMIResourceImpl/449" o-- "VirtualLinksImpl/527" : contents[0]

"VirtualLinksImpl/527" o-- "LinkedElementImpl/540" : linkedElements[0]
"VirtualLinksImpl/527" o-- "FilterImpl/548" : virtualLinks[0]
"FilterImpl/548" o- "LinkedElementImpl/540" : filteredElement

"Viewpoint/113" o-- "EReferenceImpl/453" : hiddenAttributes[0]
"Viewpoint/113" o-- "VirtualContents/447" : virtualContents

"VirtualContents/447" o-- "EPackageImpl/505" : subLists[0][0]

"ResourceSetImpl/122" o-- "EPackageRegistryImpl/672" : packageRegistry
"EPackageRegistryImpl/672" o-- "EPackageImpl/212" : "http://inria.fr/emfviews/tests/minimalref"

"EPackageImpl/212" o-- "EClassImpl/167" : eClassifiers[0]
"EPackageImpl/212" o-- "EClassImpl/188" : eClassifiers[1]

"EClassImpl/167" o-- "EReferenceImpl/345" : eStructuralFeatures[0]
"EClassImpl/188" o-- "EReferenceImpl/256" : eStructuralFeatures[0]

"EReferenceImpl/345" o-o "EReferenceImpl/256" : eOpposite

"EView/83" "metamodelManager" o--o "virtualModel" "MetamodelManager/102"
"MetamodelManager/102" o-- "Viewpoint/113" : viewpoint
"MetamodelManager/102" o-- "EPackageImpl/212" : contributingMetamodels[0]

"MetamodelManager/102" o-- "HashMap/150" : concreteToVirtualClass
"HashMap/150" o-- "HashMap$Node/163"
"HashMap/150" o-- "HashMap$Node/165"

"HashMap$Node/163" ..> "EClassImpl/167" : key
"HashMap$Node/163" ..> "EClassImpl/173" : value

"HashMap$Node/165" ..> "EClassImpl/188" : key
"HashMap$Node/165" ..> "EClassImpl/189" : value

"MetamodelManager/102" o-- "HashMap/151" : concreteToVirtualFeature
/' "MetamodelManager/102" o-- HashMap : virtualToConcreteFeature '/

"HashMap/151" o-- "HashMap$Node/254"
"HashMap$Node/254" o-- "EReferenceImpl/256" : key
"HashMap$Node/254" o-- "EReferenceImpl/259" : value

"ResourceSetImpl/122" o-- "XMIResourceImpl/678" : resources[0]

"XMIResourceImpl/678" o-- "DynamicEObjectImpl/586" : contents[0]
"XMIResourceImpl/678" o-- "DynamicEObjectImpl/604" : contents[0]
"XMIResourceImpl/678" o-- "DynamicEObjectImpl/609" : contents[0]

"DynamicEObjectImpl/586" o-- "EClassImpl/167" : eClass
"DynamicEObjectImpl/604" o-- "EClassImpl/188" : eClass
"DynamicEObjectImpl/609" o-- "EClassImpl/188" : eClass

"EView/83" "vLinkManager" o--o "virtualModel" "VirtualLinkManager/125"

"VirtualLinkManager/125" --> "ResourceSetImpl/663"
"ResourceSetImpl/663" o-- "XMIResourceImpl/656" : resources[0]
"XMIResourceImpl/656" o-- "VirtualLinksImpl/578" : contents[0]

"VirtualLinkManager/125" o-- "VirtualLinksImpl/578" : weavingModel

"VirtualLinkManager/125" --> LinksProjector : initialize()
LinksProjector o-- "EView/83" : virtualModel

"VirtualLinkManager/125" o-- "HashMap/577" : virtualLinks
"HashMap/577" o-- "HashMap$Node/582"
"HashMap$Node/582" ..> "DynamicEObjectImpl/586" : key
"HashMap$Node/582" ..> "ReproduceElementImpl/589" : value

"ReproduceElementImpl/589" o-- "DynamicEObjectImpl/586" : concreteElement
"ReproduceElementImpl/589" o-- "EStoreEPropertiesHolderImpl/621" : eProperties
"EStoreEPropertiesHolderImpl/621" o-- "EClassImpl/173" : eClass
"EStoreEPropertiesHolderImpl/621" o-- "EView/83" : eResource
"ReproduceElementImpl/589" o-- "ReproduceRule/623" : translationRule
"ReproduceElementImpl/589" o-- "ReproduceRule/623" : eStore

"HashMap/577" o-- "HashMap$Node/583"
"HashMap$Node/583" ..> "DynamicEObjectImpl/604" : key
"HashMap$Node/583" ..> "ReproduceElementImpl/605" : value

"ReproduceElementImpl/605" o-- "DynamicEObjectImpl/604" : concreteElement
"ReproduceElementImpl/605" o-- "EStoreEPropertiesHolderImpl/651" : eProperties
"EStoreEPropertiesHolderImpl/651" o-- "EClassImpl/189" : eClass
"EStoreEPropertiesHolderImpl/651" o-- "EView/83" : eResource
"ReproduceElementImpl/605" o-- "ReproduceRule/623" : translationRule
"ReproduceElementImpl/605" o-- "ReproduceRule/623" : eStore

"HashMap/577" o-- "HashMap$Node/584"
"HashMap$Node/584" ..> "DynamicEObjectImpl/609" : key
"HashMap$Node/584" ..> "ReproduceElementImpl/610" : value

"ReproduceElementImpl/610" o-- "DynamicEObjectImpl/609" : concreteElement
"ReproduceElementImpl/610" o-- "EStoreEPropertiesHolderImpl/641" : eProperties
"EStoreEPropertiesHolderImpl/641" o-- "EClassImpl/189" : eClass
"EStoreEPropertiesHolderImpl/641" o-- "EView/83" : eResource
"ReproduceElementImpl/610" o-- "ReproduceRule/623" : translationRule
"ReproduceElementImpl/610" o-- "ReproduceRule/623" : eStore

"EView/83" o-- "VirtualContents/117" : virtualContents
"VirtualContents/117" o-- "ReproduceElementImpl/589" : sublists[0][0]
"VirtualContents/117" o-- "ReproduceElementImpl/610" : sublists[0][1]
"VirtualContents/117" o-- "ReproduceElementImpl/605" : sublists[0][2]

@enduml
